In [1]:
import pandas as pd

In [2]:
category_translation = pd.read_csv("../archive/product_category_name_translation.csv")

In [3]:
category_translation.shape

(71, 2)

In [4]:
category_translation.columns

Index(['product_category_name', 'product_category_name_english'], dtype='object')

In [5]:
category_translation.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [6]:
category_translation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB

In [7]:
category_translation.describe()

       product_category_name product_category_name_english
count                     71                            71
unique                    71                            71
top             beleza_saude                 health_beauty
freq                       1                             1

In [8]:
category_translation.isnull().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

In [9]:
category_translation.duplicated().sum()

np.int64(0)

In [10]:
category_translation["product_category_name"].nunique()

71

In [11]:
category_translation["product_category_name_english"].nunique()

71

In [12]:
category_translation.to_csv("../cleaned_datasets/cleaned_category_translation.csv")